### ISSUE TITLE
Server IP cache

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1154]
For situations where the masters are down, it would be nice to have the server lists from previous sessions cached.

**Comment by minus7** [comment]
A more detailed explanation: When Teeworlds is started and the master servers are not reachable, no server list is available. The suggestion is to save the list of servers to a file on disk when it is received from the master servers, so on later starts of the game this list can be used as a fallback.
(@winterismute)

**Comment by heinrich5991** [comment]
Always reading the server list from disk and only updating it with the master servers seems to be the best version – it can start up immediately and only later request the server lists.

**Comment by winterismute** [comment]
Ok, I had some more free time.
I have decided to do this first and then when this is kind of finalized move to #1281 . The commit, if I did not overlook something fundamental, should implement the feature. We read the initial servers from a file, and after every server list update, we also save to file to update this "cache".

The only thing is that I can not test it fully (I can only verify stuff gets loaded and saved) because from master I am afraid I have to do something in order to get a correct list of server from the master servers because there was some retro-compatibility going on. Could somebody point me to what I should change in the code to have server coming from the master servers?

**Comment by Henningstone** [comment]
I wonder if anybody is still interested in this?

I implemented it here: https://github.com/Henningstone/AllTheHaxx/blob/master/src/engine/client/serverbrowser.cpp#L610-L710
It works very well and saves quite *everything*. I load the serverlist from cache at client startup instead of requesting it, so the client provides it instantly. No need to wait 20 seconds for 1000 servers any longer.

I can create a revised version for vanilla 0.7 if you like. To try it, just download and compile [AllTheHaxx](https://github.com/Henningstone/AllTheHaxx) source code ;)
