### ISSUE TITLE
Don't reload serverlist any time when switching to it from an other tab or menupage

### ISSUE THREAD

**Issue by Henningstone** [teeworlds/teeworlds#1281]
Wouldn't be it better if the serverlist won't reload any time we are switching to it from an other tab, i.e. LAN-Servers Favourites or the Settings page?
This would make it a lot faster and maybe more convenient for the user to choose a server from the list, if he was previously at for example the favourites or the settings.
For me it takes nearly ten seconds (maybe ~8) until all the servers are loaded again and I can select one, which is, in my opinion, quite annoying.

**Comment by winterismute** [comment]
I think this could be added by just:
- Storing the timestamp of when a refresh (either internet or LAN) is performed
- When tabs are switched and a refresh is triggered, we check if the last refresh of that type happened more than X seconds ago. If yes, request a refresh
- X could be a new configurable parameter with a default value of, uhm, 5 seconds? Or even 0.
- If user clicks on the refresh button expressively, perform ALWAYS a refresh, although I am not sure about this.

What do you think? It would be fairly easy to implement and I would do that myself.

**Comment by heinrich5991** [comment]
My proposal for this is: Never reload when the user is just clicking tabs, maybe merely display a note if you have a stale server list.

**Comment by minus7** [comment]
Include persisting to disk too, which would take care of #1154

**Comment by winterismute** [comment]
Hey, I am currently working on this, implementing a no-reload policy while switching as suggested by @heinrich5991, it is actually more difficult than I thought because we need now to remember N lists of servers while the current code is made so that only one is kept and constantly cleared on refresh/tab switching.
@minus7 I did not understand what you mean, the issue you linked does not say anything about saving to disk, it would be great if you could explain it.

**Comment by winterismute** [comment]
Ok I think I understood. I will try to deal with this and add the part about #1154
