### ISSUE TITLE
0.6.4 should contain some protection from IP spoofing

### ISSUE THREAD

**Issue by tbu-** [teeworlds/teeworlds#1380]
I'm thinking of a lightweight and backward-compatible version of #986.
See https://www.teeworlds.com/forum/viewtopic.php?id=11493, there are people exploiting this in the wild.

**Comment by Meskalin** [comment]
Thats not true. There is no real abusing of it. Well, in 0.7 it is fixed anyways, i don't see the point in breaking any compabilities in 0.6.

**Comment by Henningstone** [comment]
I see no way how to completely fix it in 0.6 without breaking compatibilities, because too much network-stuff needs to be changed in any way. Additionally, this would kill most of the nice 0.6 mods for a time since they are incompatible to the masters and need to be updated.

**Comment by heinrich5991** [comment]
@Henningstone You can fix it without breaking compatiblity, just look at DDNet.

@meskalin
>Thats not true. There is no real abusing of it. Well, in 0.7 it is fixed anyways, i don't see the point in breaking any compabilities in 0.6.

I find it interesting that you say that when you're explicitely mentioned as abusing it in that post.

**Comment by Meskalin** [comment]
The funny thing about it is that i didnt even do anything.

Well however, that was not meant to be a "please dont fix this" but a information for him that it is already fixed actually but most likely wont be in 0.6 anymore.

Plus its rude to snitch names of people, because many other where not even mentioned even when they were the ones who abused it.

**Comment by oy** [comment]
The stuff that has been done for 0.64 should suffice. Invalid.
