### ISSUE TITLE
Version server field for 0.6.3 suboptimal

### ISSUE THREAD

**Issue by heinrich5991** [teeworlds/teeworlds#1392]
It should be `0.6.2`, because the version server announces `0.6.2` which is due to 0.6.3 being a non-critical update.

I think I asked minus to correct this once, but it seems it has been uncorrected. The binaries and source code on teeworlds.com all use the 0.6.2 "version server version".

**Comment by oy** [comment]
No, the actual one is correct, it should be 0.6.3 as it's a new release - doesn't matter if it's critical or not. Though I would consider 2 crashes fixed in the client critical.

The binaries on the website should be fixed. And while on it, the provided sources there as well, as they contain object files which should NOT be in there.

**Comment by heinrich5991** [comment]
Can we talk about this on IRC, please?
