### ISSUE TITLE
Add Antiping feature

### ISSUE THREAD

**Issue by Zwelf** [teeworlds/teeworlds#1409]
This great feature is one of the best of the ddnet-client. Implementing this into the standard client would be nice.

**Comment by east** [comment]
Just to clearify. "Antiping" is an improvement of the client-side prediction. Afaik it provides a better prediction for projectiles (e.g. grenade path & explosion) and hammer. More accurate projectile angles are used (server modification required).
It also provides a player prediction, which probably is not really useful in vanilla, since the prediction fails when a player suddenly changes his moving direction (looks laggy).

**Comment by pielover88888** [comment]
I believe antiping for player prediction should also be provided but discouraged, in some situations it may be wanted (e.g. < 30ms latency, with antiping, makes it feel like LAN), but leave the option, and make sure both projectile or weapon, and player predictions, can be enabled separately



From: east
Sent: ‎Tuesday‎, ‎September‎ ‎29‎, ‎2015 ‎3‎:‎59‎ ‎AM
To: teeworlds/teeworlds





Just to clearify. "Antiping" is an improvement of the client-side prediction. Afaik it provides a better prediction for projectiles (e.g. grenade path & explosion) and hammer. More accurate projectile angles are used (server modification required).
It also provides a player prediction, which probably is not really useful in vanilla, since the prediction fails when a player suddenly changes his moving direction (looks laggy).

**Comment by oy** [comment]
Won't fix - talked before, wouldn't work properly.

**Comment by Zwelf** [comment]
Hm, antiping is implemented in the ddnet-client and works good for me. In my opinion it is like the dynamic cam. It is a great feature especially for advanced player, but you don't want to give it to new players, because it could confuse them.

**Comment by MegaManSec** [comment]
Teeworlds isn't ddnet. Have you tried using it on Vanilla?
As east said, it's not useful in Vanilla, which is what this game is made for..

**Comment by Zwelf** [comment]
East pointed out, that the prediction of players may not be useful, but antiping also includes prediction of projectiles. And yes, I am using antiping in Vanilla as well.

**Comment by TheRealOrangus** [comment]
Exactly, what about prediction for projectiles only? This _would_ work properly.

**Comment by heinrich5991** [comment]
They would be out of sync with the other players though..

**Comment by TheRealOrangus** [comment]
And? I think it would more useful because players would be able to avoid incoming projectiles.
Besides, the _"own"_ character is already predicted, and out of sync, isn't it?

**Comment by MegaManSec** [comment]
If you hit somebody with the grenade, your client will show them being moved away. But if you didn't really hit the player, then it'll update in a few ms to see them still going the same way..

**Comment by TheRealOrangus** [comment]
> If you hit somebody with the grenade, your client will show them being moved away.

Right, didn't think about this...

> But if you didn't really hit the player, then it'll update in a few ms to see them still going the same way..

I didn't understand this sentence.

**Comment by MegaManSec** [comment]
In a few ms when the server sends you back what really happened, your client will just completely disregard the prediction, which is not a good thing. Have you seen how this works with a 400-ping network like I have on European servers?

**Comment by pielover88888** [comment]
Pleade keep in mind explosions pushing tees is 'weapon prediction' seperate from 'preojectile prediction'
