### ISSUE TITLE
Hook as part of skin

### ISSUE THREAD

**Issue by TheRealOrangus** [teeworlds/teeworlds#1419]
I think it would be nice if hook would be unique for each skin, Why all kinds of tees came from everywhere have the same hook?

For example, a mummy skin, why is mummy using metal hook? Hook of mummy would look rather like some old piece of fabric, if you know I mean. For a spidertee skin, it could be a web.

**Comment by pielover88888** [comment]
But for a mummy type skin to be fabric, the metal sound of the hook would be odd, right?

**Comment by TheRealOrangus** [comment]
Oh yeah, well then the hook sound, should be part of skin, too.
For standard skins metal sound is okay I guess.

**Comment by android272** [comment]
![](http://orig08.deviantart.net/6949/f/2015/292/4/2/teeworlds_chain_hook_by_android272-d9dex26.png)
![](http://orig10.deviantart.net/f2ba/f/2015/292/3/6/teeworlds_rope_hook_by_android272-d9deww2.png)
![](http://orig09.deviantart.net/6bc1/f/2015/292/e/0/teeworlds_razor_hook_by_android272-d9dewxj.png)

**Comment by TheRealOrangus** [comment]
Yeah, something like that, drawn well.

P.S. chain isn't separated to 2 images, but is a single one(not sure about 0.7 though).

**Comment by android272** [comment]
These chains are from my [Revamp Hooks [With Source Files]](https://www.teeworlds.com/forum/viewtopic.php?id=11600) forum post. The reason i spit up the chains was so that you could put the them back together ingame and make them bend around objects is they would in the real world.  If you look at the skins this is exactly how they are constructed.  

check out the new [Body](https://github.com/teeworlds/teeworlds/tree/master/datasrc/skins/body), [decoration](https://github.com/teeworlds/teeworlds/tree/master/datasrc/skins/decoration), [eyes](https://github.com/teeworlds/teeworlds/tree/master/datasrc/skins/eyes), [feet](https://github.com/teeworlds/teeworlds/tree/master/datasrc/skins/eyes), [hands](https://github.com/teeworlds/teeworlds/tree/master/datasrc/skins/hands), [marking](https://github.com/teeworlds/teeworlds/tree/master/datasrc/skins/marking) skins.

**Comment by oy** [comment]
Won't fix the hook won't be part of the skin and stay part of the game like weapons etc. - keeping it simple.

**Comment by android272** [comment]
>Won't fix the hook won't be part of the skin and stay part of the game like weapons etc. - keeping it simple.

Would you kindly explain why the hook won't be apart of the tee skin? Also would you please elaborate on how doing this would somehow be complex in anyway?  How is keeping all the objects in one singular sprite more simple then separating them out?

This is actually a great idea and I think it should be implemented. It would be one more way to make your Tee yours. It would be just like markings or decorations.

**Comment by ixPost** [comment]
> Won't fix the hook won't be part of the skin and stay part of the game like weapons etc. - keeping it simple.

How is that complicated!?!? There are all sorts of tee skin settings and at least changing the color of the chain(hook) wold be _very_ simple!

**Comment by android272** [comment]
@ixPost "it's complicated" and "Keep it Simple, Stupid" is code for I don't want to do it. It you want it done, you need to do the work yourself. I have a lot of things that I want todo to the skin system, but I don't have the time nor do I Know C/++ which takes time. One day maybe I will take this and other features on.

**Comment by ixPost** [comment]
But someone else can do it for you, right?

**Comment by android272** [comment]
Oh sure if someone had the time and the know how to write a patch the Teewords team should accept it. They should, as this would be a very nice feature for customization.

**Comment by ixPost** [comment]
Where is the skin code?

**Comment by android272** [comment]
https://github.com/android272/teeworlds/blob/teeskin/datasrc/content.py

**Comment by android272** [comment]
I can not remember how this code works at all. I was working on some stuff back in 2018.
