### ISSUE TITLE
Add broadcast command back again

### ISSUE THREAD

**Issue by BigPack** [teeworlds/teeworlds#1438]
Because it's a huge disadvantage for mods and server admins.

https://www.teeworlds.com/forum/viewtopic.php?pid=116804

**Comment by H-M-H** [comment]
and while adding this implement newline support as suggested here: https://www.teeworlds.com/forum/viewtopic.php?pid=116803#p116803

**Comment by heinrich5991** [comment]
I believe the old broadcast did have newline support.

**Comment by H-M-H** [comment]
Actually not: https://github.com/teeworlds/teeworlds/blob/0.6/src/game/server/gamecontext.cpp#L1088

This is why it has been added to ddnet: https://github.com/ddnet/ddnet/commit/4b70e195c12be3b3c95e5914159ab48e835761cb

**Comment by xushTW** [comment]
I'm not in for the reimplementation.. Things are clearer like that in vanilla.

**Comment by heinrich5991** [comment]
@H-M-H Yea, the broadcast command doesn't have that, you're right. The server could send newlines to the clients though.

**Comment by H-M-H** [comment]
@heinrich5991 yes, the server was able to send newlines but it was not possible to give them as input of the broadcastcommand ^^
@xushTW this might be true but as already pointed out it is not too nice for mods and server administrators. (Something I dream of is letting the server send custom windows/dialogs to the client but well as we are already discussing about reimplementing broadcast...)

**Comment by oy** [comment]
Won't fix, the messages are integrated into the client now - don't care about mods.

**Comment by Zwelf** [comment]
Maybe you should care about server admins...

**Comment by Duracraft** [comment]
Or about the community...

Everbody want the broadcast command back in teeworlds, except xushTW.
But oy make his own decisions and don't care about the teeworlds community.

**Comment by xushTW** [comment]
Who said I don't want it? It's not about personal opinions, you have to have an objective view: The broadcast command it not needed in vanilla and mods never got much official support. 

I'd personally prefer to keep the broadcasting aswell, just saying.

**Comment by Duracraft** [comment]
Server admins could still use this command to announce something. Also in vanilla.

**Comment by xushTW** [comment]
Server admins could use the chat aswell.

**Comment by TheRealOrangus** [comment]
Players pay less attention to the chat, and may miss something, so the server admins have to spam the chat to announce something?

**Comment by android272** [comment]
> Won't fix, the messages are integrated into the client now - don't care about mods.

Do you know where Minecraft would be if Mojang said that they don't care for mods?  Nobody would be playing it today.  Mods are what makes Minecraft Minecraft and telling from the many Teeworlds statistics out there mods make Teeworlds as well. 

I completely understand only wanting to work on things your interested in and things you think will make the game better.  But to actively shoot down ideas that may make mods and or Teeworlds better just because you don't like modes makes no since what so ever. 

If you don't want to work on a feature then put it on the shelf until someone else's has has the time to employment it.  This is an open source game if it is a feature that everyone wants eventually someone will sit down and make it.

**Comment by ObaniGemini** [comment]
@android272 : I'm with you on that point

**Comment by ChillerDragon** [comment]
Some years passed by...
Is there any chance we can add the broadcast back again? c:
