### ISSUE TITLE
Store map config in maps

### ISSUE THREAD

**Issue by Zwelf** [teeworlds/teeworlds#1451]
For example game type, score limit, maximal players can be stored in maps. All in all configs related to the map. In my opinion this is a very helpful feature for server administrator.

**Comment by ObaniGemini** [comment]
I don't understand how it would be helpful

**Comment by necropotame** [comment]
Putting these parameters in the map will make harder to tune them. On the other side, this allows to have different time limit for each map, when your server use map rotation.
Since this is a server only issue, it can be solved by using an additional file with these informations (line in InfectionClass). It's not really important to have this feature in the vanilla server.

**Comment by heinrich5991** [comment]
@necropotame I'm not sure I follow. If anything, this should make it easier to set up a server with map-specific settings. Tuning the settings won't become harder, it will just become unnecessary in the general case.

**Comment by BotoX** [comment]
maps changing rcon passwords, I'm calling it.

**Comment by heinrich5991** [comment]
@BotoX DDNet has a simple whitelist for that stuff: https://github.com/ddnet/ddnet/blob/master/src/game/variables.h#L155 (all config variables with the flag `CFGFLAG_GAME` can be set from a map).

**Comment by oy** [comment]
Won't fix, already proposed in the past.
