### ISSUE TITLE
Send client name on server connect.

### ISSUE THREAD

**Issue by Zwelf** [teeworlds/teeworlds#1453]
Something like a 16-Byte string to identifier different clients.

**Comment by prathje** [comment]
Ans reasons? As teeworlds does not have an account system I wonder what the name could identify and why the server should not wait for the whole client information to be sent?

**Comment by Zwelf** [comment]
Hm, I was thinking about this like an additional client information. And it helps (modded) servers to check if the client support some features.

**Comment by prathje** [comment]
Sry, I misunderstood you. If you got a server which may enable features for a specific client you might want to send your custom string anyway and detect your client.
I do not think that this is a feature which should be implemented in Vanilla-Teeworlds in order to keep it clean from mods.  
However, this sounds more like a proposed ***convention for modders*** to interchange information about different client and server mods.

**Comment by Zwelf** [comment]
In my opinion this is like the gametype string for servers and you can visualize the spreading of clients.

**Comment by CytraL** [comment]
Umm something like point "2.1": https://twmapeditor.wordpress.com/information-for-modders/ no?

**Comment by oy** [comment]
Won't fix. Client sends net version which is all that matters.
