### ISSUE TITLE
Typing in F1 or F2 console while selecting the "Host address" textfield writes in both

### ISSUE THREAD

**Issue by jordy-ruiz** [teeworlds/teeworlds#1465]
using 0.7 trunk

**Comment by Henningstone** [comment]
This behavior was introduced by commit 373f98ea3d1b054ecc7058a3431a4c5c2064084b.
Using `Input()->NumEvents()`/`Input()->GetEvent(i)` instead of `m_NumInputEvents`/`m_aInputEvents[i]` circumvents the blocking mechanism implemented by the input stack, thus the console can't prevent the input from going into the menus.

 ([»Lines from my example](https://github.com/teeworlds/teeworlds/commit/373f98ea3d1b054ecc7058a3431a4c5c2064084b#diff-cad6690c312d4ab80e91a046cdbb5becL455) - there are more)
