### ISSUE TITLE
something don't work well in the general rendering

### ISSUE THREAD

**Issue by Irradius** [teeworlds/teeworlds#1506]
It seems very strange that a little simple game like Teeworlds warm the graphic card more than a 3d game (for examples Minetest).
There is definitely some errors that uselessly tire (stress) the graphics engine

**Comment by xushWT** [comment]
Heat is not a reliable indicator for graphic card stress. We need numbers.

PS: I do not have that issue.

**Comment by Irradius** [comment]
is possible that the graphic engine haven't any memory cache, so repeat continuously the same calculation?    because the warm happen also in the editor or in the simple GUI, without playing!

**Comment by H-M-H** [comment]
Yes, this is the case, look at https://github.com/teeworlds/teeworlds/blob/16965e4bd6e85488fffa1d8c91530b037b60fed1/src/game/client/render_map.cpp#L333 for example. Also about every GUI item is a function repeatedly called.

You might be interested into this issue I opened for DDNet: https://github.com/ddnet/ddnet/issues/811  the situation for Teeworlds is probably similar.

**Comment by Irradius** [comment]
Yes, I have read already time ago that issue on DDNet, and I subscribed to receiving notifications, because I am very interested to this improvement.
@Jupeyy made a full port to opengl 3.3 using shaders and buffering TileLayers into the opengl buffer objects,(And glew) it remove CPU bottleneck while playing, but @H-M-H noticed that menus like the serverbrowser are really slow/laggy and sometimes text is not rendered correctly.

**Comment by Jupeyy** [comment]
Batching or caching might reduce the time between the actual rendering(so might also improve the frame rate, depending or how much the render time takes), but i doubt it improves the GPU render time alot, nor i think it will reduce the heat of the GPU(or atleast not alot, ofc memory swaping and such things require more power too).

Are you sure you monitored the GPU temperature. If you just looked at some GPU usage, are you sure you program is designed to actual monitor the GPU usage(often such programs say 99% usage, because the GPU might be busy by other stuff then rendering etc.)

Also i think you should overestimate 3D games over 2D games, the rasterizer will be used for both and the fragment process depends more on amount of textures used etc.

My GPU for example is never at full use with teeworlds, because my CPU is bottlenecking (because not everything is buffered or cached in teeworlds, or other reasons)

Actually except the RenderTilemap and some smaller things teeworlds should run extremly low power depending on the fps limit you set. are you sure you are limiting it?

Else give me an example 3D with FPS count, GPU usage etc and you teeworlds FPS count, GPU usage etc.

**Comment by oy** [comment]
You have to enable vsync - otherwise it will render as many frames as possible. It doesn't matter if you're in the game, the editor or the menu.
