### ISSUE TITLE
Current state of Teeworlds + DDNet

### ISSUE THREAD

**Issue by loru** [teeworlds/teeworlds#1514]
# Current state of Teeworlds
Dear oy, dear developers, Teeworlds, DDNet,
This issue will not address any bug whatsoever. It is only about the community & the game itself. Please take the time to read this post entirely before commenting. Thank you!

![screen shot 2018-06-10 at 4 28 05 pm](https://user-images.githubusercontent.com/19887885/41202580-4dd3fc88-6ccb-11e8-9816-1b0bca1971e4.png)

Hi. 
You might have seen me in the game under the names: Gabee, [iPod clan] Gabou, etc, our clan participated in zChaos, iDDRace and so on. I wanted to discuss an issue that concerns everyone and not only me.

##  Teeworlds, as the main project, is stalling
Needless to say that if you take a look at the ["recent" commits](https://github.com/teeworlds/teeworlds/commits/master) you will easily realize that it is not very active anymore, only oy is committing. 0.7 is a myth, there has been nothing new in the last 4 years (minimum), the last releases were only about security. No new feature, no improvement, even 0.6.3 -> 0.6.4 breaks the fonts within the game. So, yes, I could open an issue for that but… is it gonna get fixed? I'm still playing on 0.6.3 in the meantime, because there are so many security holes that my font bug is nothing compared to that. 

## What about DDNet?
You do not need a description of what is DDNet, if you are an active player on Teeworlds, you _know_ what it is, but still

* DDNet is a mod of Teeworlds, both a client & server
* DDNet offers many features Teeworlds lacks
* DDNet offers security workarounds and other workarounds
* DDNet is bloated as fuck, full of useless features, ugly and so different from the vanilla client that I'm not even using it even tho I should.

Why am I talking about DDNet? In 2018, they are still active, keep "improving" (this can be subjective, but that's not the point here), and even Teeworlds developers now participate in DDNet's development.

Now, from what I've been told, it seems that the Teeworlds team & the DDNet are not coming along on many points regarding Teeworlds and this is a problem as the "fork" is improving and is restricted because it cannot break compatibility with the original client that is not active anymore…
Do you see it coming?

##  I am proposing a merge, DDNet and Teeworlds
Whaaaat? NO WHYYYY? No, really, please hear me out before reacting!

DDNet has a lot of participants, there are 5-10ish developers on the #developer (Discord), IRC etc. They are here, they are around and they're active, playing, coding.

Now, if that is supposed to happen, it has to be properly handled. DDNet in its current state cannot become the new vanilla client on Teeworlds because:

* It is ugly (colors, in text, in the interface)
* It has too many functions (you can change the font in game, the red laser, you have two server lists…)
* It doesn't make sense, at all
* And I am personally forced to play full screen, it doesn't support the small window I'm used to play with

## Teeworlds is alive
Look at the current game, the facts, what is going on. When I run my teeworlds client, this is what I see (I have a bad reception here, don't mind the ping:

![screen shot 2018-06-10 at 4 10 24 pm](https://user-images.githubusercontent.com/19887885/41202574-1f8d327c-6ccb-11e8-9ca5-ece7f8a9c95e.png)

No matter how much you hate the mods (as in the customization, not the moderation, heh), you can only see 3 official servers here, okay, let's cheat a little, let's add the zCatch because it uses ctf5 as well. So 5 servers? Out of?
Whatever you think regarding Teeworlds VS DDnet, it doesn't matter to the players. IF you discover teeworlds and play you will play dm, you will play ctf, but after some time it gets boring so you dig into it. I love the vanilla concept, but for me this also include races etc.

## My proposal for DDNet:
* Clean DDNet so it looks exactly like Teeworlds
* Seriously, drop all these useless features. It was nice when we were using MSN with all the customized fonts & personalized smileys that were taking half the screen, it's 2018, we all use the same interface because it's been polished. Vanilla looks good, DDNet looks bad.
* Make it official: All the names in DD, change them: gametype="ctf, dm, race, block, city," and so on, so it looks organized
* All these skins are fun but there are so many of them really…
* I'm a player, I know what it is like to code but seriously, don't see the limitations because of the code, you can make it happen, do it, clean that interface: the ping color, the huge tabbed 64p list?
* You need to be a little more organized, the interface is a mess, but I think you got the point
* Basically a lot, but you gotta earn this.

Basically a vanilla client -like, but based on DDNet. Not removing the current one, but making a light version of it?

I know I might not have the legitimacy to talk to you guys that way but as a player, that is how I feel

## My proposal for Teeworlds:
* Once DDNet is clean enough (it's not gonna be done tomorrow), give it a try, please.
* Discuss with DDNet as it overtook the current community. It is huge. Really, have a look, don't hate, don't judge, just see and get along together. We're the same people playing the same game.
* Don't disappear, get a consensus and merge. Of course there can be conditions. 

Hopefully this won't get ditched or closed in 2 hours, there is a lot to do and it has to happen. I've been playing on Teeworlds for 5+ years and I'm not gonna stop today but seriously. Do something to kick this game! It's a game that only weights 10MB approx, my ~/.teeworlds is even bigger because of all the maps & demos.

<3

**Comment by ChillerDragon** [comment]
Its teeworlds not raceworlds lol.
DDNet should stay a mod and we can take all the good none race features from ddnet into teeworlds (idk if there are any missing because i don't know the current state of 0.7).

I see another problem here. The reason why teeworlds devs become ddnet devs is because there is an better chance of getting things merged. The official teeworlds repo makes the life of contributors hard.

**Comment by android272** [comment]
I don't see why race can't be a game type. TW needs more game types anyways why not add racing to that. Why does TW have to remain DM and CTF only? Broaden the game a little. It is what people seem to want and it will definitely increase the number of players who play DM and CTF as when you get bored of racing you will hop into another game and vice versa. We need to get more people playing or TW will officially die. None of us wants this to happen but it will happen eventually. Vanilla needs to change and it needs to start with the Keep it simple stupid and the 1.0 was perfect don't change it mindsets. TW is not perfect, no project is. There will always be improvements to be made.

**Comment by xushWT** [comment]
Has your clan also contributed to XXLiDDRace+++**IMBA_MOD?

**Comment by lschierbach** [comment]
I like the Idea, but this is not going to happen.

The release of the vanilla Teeworlds Client on Steam was a disaster. It should've been planned a lot more, not just "let's see what happens, if we release this game without any changes on Steam".

Also the Community is divided. I don't get the hate for DDnet, at the moment it's the only part of Teeworlds that's actively developing the game.

What I also don't get is why so many people don't want Teeworlds to "get taken over by DDnet". Look at the serverbrowser. It already is. And with blocking every change like this, the game will never gain any more popularity. DDrace should be the main mod. The standard settings in the default Client are a joke. Whoever downloads it, will just see a lot of empty DM and CTF Servers.

So my suggestion is:

1.) Make the serverbrowser filter by gamemode. The box for "Standardgamemode" is not a good solution for this. The player should be able to say "I want to play DDrace. I want to play Block. I want to play ctf, etc. etc.".

2.) Clean up the gamemodes. You don't have to change the code of them. Just the name that will appear. It's confusing for new players to have three different variations of DDrace, even tho it makes just small differences, new Players won't even notice. When a Server is running on "blocking" call it like that. It's not DDrace, it's "blocking".

This is totality possible to do. When I've time besides college & work I'll do that if you think as I do.

But I'm not optimistic tbh. This would need to have support from the original Teeworlds-developer which is not going to happen I guess

**Comment by cinaera** [comment]
There seems to be the base assumption that main goal of this project is to gather and keep players, which is not the case compared to commercial multiplayer games. As far as I understand the primary goal was to realize a game concept which was done, the current project is literally maintaining and slight improvements.

For the DDNet team I don't see that the proposal would be attractive due to mismatching goals. Even if it would be possible to align them, the implementation efforts would pay off in lets say one year beside losing a whole bunch of content (map compatiblity and scores) making it very unattractive imo.

**Comment by android272** [comment]
@cinaera what are the DDNet team's goals? What are Teeworlds' goals?

**Comment by teetow** [comment]
I'll leave the decision to the active maintainers, but we indeed didn't build Teeworlds with any other goal than to make a game we knew was fun to play. Once that was done, we stepped down and let the game live its own life. Anything that happens to it is perfectly fine.

I'd just look at it from the perspective of the player. What kind of experience are you looking to build? If you would sum up Teeworlds, what would it be? For us, the unofficial tagline was always "Super Mario Quake." It was easy to define, easy to understand, and set the right expectations in the player's head. As long as you keep that perspective, you're all good.

**Comment by lschierbach** [comment]
@teetow if it's like this I don't get the choice to release the game on steam. The problem is: It isn't fun to play if the playerbase is shrinking.

@cinaera I don't understand your point on the backward compatibility. It is not that hard to filter the style of the scoreboard by the gamemode you're playing. In fact, DDNet already does this. It would be a good first step in my opinion, to make the DDNet client the default one. It's very confusing for new players when they have to decide between "Teeworlds" and "DDNet". As DDNet is Teeworlds with more features I don't see the problem in doing this.

Most players are blocking or racing. When a new player launches Teeworlds, it doesn't make sense to call DDRace a "not standard gametype". Teeworlds is much more then ctf, dm, or tdm.

**Comment by loru** [comment]
This, exactly!

DDNet has a lot of features that are very cool but some options in the interface are just too much. A more polished version of the DDNet client would be neat and would be a good replacement for Teeworlds. Or an extended version. Call it what you want. 

When I'm on the servers, I'm the only one playing vanilla.. :-/ I think it's fair to say that DDNet already overcame Teeworlds (the softwares, because the base/users are the same). Teeworlds should integrate all these changes that everyone wants.

**Comment by loru** [comment]
@teetow : the goal here is to keep Teeworlds alive instead of splitting between Teeworlds & DDNet: everyone plays on DDNet, I'm pretty sure even you once tried a race map or a block map. It is fun, it is cool, and there are so many players… you can't ignore that fact.

The goal here is to have a vanilla client that also supports the "block" and "race" gametypes out of the box. It should receive the security patches too. It should be more active, just like DDNet is.

The gameplay or the playing experience should never get affected by these changes.

**Comment by cinaera** [comment]
> I don't get the choice to release the game on steam

(Not towards me but still trying to answer it.) Steam only provides an additional platform for distribution here. I don't think any further integration was planned or will appear in the future. Therefore it didn't affect the game at all.

@lschierbach I meant that integrating ddrace/ddnet into the current teeworlds master would require adjustments additionally to possible physics breakage, map protocol changes etc. All this will require porting of the current mapbase (lets say ddnet maps) to the new master version which possible map breakage due to physics changes. This also renders all current scores from the ddnet network useless, see current discussions regarding grenade explosion fixes, weak/strong, etc.
Ignoring the current ddracenetwork would ease the integration, I agree here, but wouldn't really solve the 'competition' between ddnet and teeworlds.

@android272 From my understand teeworlds had a fixed scope as teetow already mentioned focusing on fast paced shooting mechanics. There haven't be a strong focus on trying to make it an highly competitive product including matchmaking, ranking, tutorials etc. which would be key factors for creating a more 'successful' (in terms of player counts) product.
On the other hand ddracenetwork lives from constant map updates (highly community driven therefore also fluctuating quality) and providing some sort of account system. It has a much higher focus on keeping an active playerbase compared to current teeworlds development, which aims more on polishing and creating a more standalone, decentralized game.

I would argue that ddnet is a more attractive product from the player side, also looking at the player counts. Even though it lives in the ecosystem of the main teeworlds game the scopes of the two projects don't really overlap very well from my perspective of the current situation.

**Comment by Stitch626** [comment]
I didn't read everything here, but I'm on TW-Dev's side. DDNet came, killed the almost whole game, and if it finally takes over tw, it would kill the game entirely.  I also don't like some facts about tw itself, but ddnet is a mess (concerning code style, stability and resource comsumption). Sure, it has SDL2 and maybe other little things which could be added to vanilla, but thats it. One thing I've seen was that private hosted servers (whatever gametype) disappeared almost complete right after ddnet appeared. You are right, ddnet has already taken over but thats bad I think. Teeworlds is Teeworlds and not DDNet. 
I'd personally like to make DDNet and THE WHOLE BLOCK COMMUNITY disappear. Why? Because the block community is rude (they are, really) and DDNet has a position where it has too much power. Today we have a good example for those 'powers': The masterservers are being attacked by someone and the ddnet one just blocks everything from outside while DDNet's own servers are still listed. I hope you understand.

**Comment by PathosEthosLogos** [comment]
Teeworlds should be considered a fork of DDNet instead. Teeworlds is long lost.

**Comment by Henningstone** [comment]
@PathosEthosLogos uhm, that's not how "forks" work... and that's also not how mods work, wanting the original game to gtfo just because your mod got kinda popular...

**Comment by PathosEthosLogos** [comment]
Haha I understand how forks work.

I don't want the original game to be lost at all, but I face the reality that it's lost. I think you should too.

Comparing DDNet to vanilla is congruent to comparing an adult to a child.

Just let DDNet be.

**Comment by savander** [comment]
Every mode is part of the "core game", since official statement from 2003 FAQ said that, the game will be modable. 
![63f02354e396bc80a1f5dc9011b14486](https://user-images.githubusercontent.com/2012010/41814655-79b6a52e-7754-11e8-8b38-a6fab9228315.png)

**Comment by android272** [comment]
Can we switch from talking about whether or no Teeworlds and DDNet should be merged and start talking about what could/should be merged? I am 99% new to DDNet. I only played it once just the other day. As far as I can tell not being apart of the community or looking at code and knowing the technical additions, DDNet has some minor setting additions, the serverbrowser/UI is slightly different, but primarily has a race game type that has very different rules that do not involve killing other tees. I do not see why any of the DDNet game types should not be added to TW.  There are a lot of game types I would like to see come to TW... ok just found the "novice" in the search box there are more game types. Not exactly sure why that is even there by default. 

Anyway, I think that the games should be merged to some semblance of the word. I don't know what should be added or subtracted from either game. But I would like to see some progress on TW so what in everyone's viewpoint should be done? What should be added? What needs to not be merged? What needs to change about TW?

I personally do not like the KEEP IT SIMPLE STUPID! NO MODS! NO CHANGES! mentality of Teeworlds. I think that needs to go.

**Comment by def-** [comment]
> ok just found the "novice" in the search box there are more game types. Not exactly sure why that is even there by default.

So that new players don't immediately start on a Brutal/Insane server and get demotivated.

**Comment by heinrich5991** [comment]
>Today we have a good example for those 'powers': The masterservers are being attacked by someone and the ddnet one just blocks everything from outside while DDNet's own servers are still listed. I hope you understand.

The right response would be to fix the underlying problem of the master server protocol. It currently allows one bad actor to effectively remove all servers from a master server list. But Teeworlds doesn't seem to have the resources to fix the master server protocol – and this is one of the things this issue points out.

**Comment by Henningstone** [comment]
> The right response would be to fix the underlying problem of the master server protocol. It currently allows one bad actor to effectively remove all servers from a master server list. But Teeworlds doesn't seem to have the resources to fix the master server protocol – and this is one of the things this issue points out.

There are certainly enough skilled developers in the community who could come up with a solution to this, but the problem is that nowadays many feel like it's more unlikely than likely for it to get accepted in vanilla, which is pretty demotivating.

**Comment by lschierbach** [comment]
> There are certainly enough skilled developers in the community who could come up with a solution to this, but the problem is that nowadays many feel like it's more unlikely than likely for it to get accepted in vanilla, which is pretty demotivating.

^ this

I wouldn't call it "unlikely", I would call it like talking to a brick wall. This thread just proofs it.

On one hand we have on average about 200 to 300 people playing DDNet. On the other we have maybe a few dozen players playing the standardmodes. In my opinion it's just pure ideology to not allow the fusion of Teeworlds and DDNet.

**Comment by teetow** [comment]
If it's indeed the case that DDNet is significantly more popular, why merge them at all? I'm not sure I see the benefit of adding "a few dozen players" to the player pool.

Also, what is the basis for the assumption that the typical player of those two modes will indeed welcome a merge? Do we have data to suggest that people jump freely between the modes, or do they mostly stick to one or the other?

Again, I'm not arguing for or against, I'm just trying to understand the reasoning.

**Comment by loru** [comment]
@Stitch626 This is true. The block "communities" (there's not only one… sadly) are a bit annoying. People ddosing, hacking the servers etc, they're into the "fight". Still, should we stop? No.

There are all the downsides you want: they make custom ddnet clients including backdoors, remote-control, basically distributing a botnet, and they make people for that. Yes, it's terrible. Now, because few (it's a minority) are causing trouble, we should stop, we should not exist? Wow, thank you, we hope we'll never say that about you, because the plan is to merge, not to be ennemies. ;-)

___

@teetow "If it's indeed the case that DDNet is significantly more popular, why merge them at all?" ->
Because DDNet is improving the game. Yes, the term is very subjective here, but DDNet is giving a few improvements, in terms of security & stability. The rest (visual features etc), I don't really mind.

If DDNet wants to keep improving, if not merging with Teeworlds, if Teeworlds doesn't follow DDNet, then there will be a broken design. Using Teeworlds, you won't be able to use the DDNet servers, & vice-versa. YES, this is a problem! We're a community, one community, playing the same game. We all have our preferences but we're in the same boat here. 

___

This is not a problem of ressources, or skills. It's a political problem. 
Teeworlds doesn't want its child.
Teeworlds doesn't want the race gametype everyone plays, even the devs played race at least once.
Teeworlds doesn't want new things to be added.
Teeworlds wants to die?
And yet, they promoted Teeworlds on steam.


We could go on, and be full-ddnet, separated from teeworlds, but this should not happen. It's the last step. Kinda like openoffice & libreoffice, when openoffice died. Teeworlds is going to die, and you know it. 

We NEED this, Teeworlds needs this. It is not dead yet, DO something, it is our last resort, for all of us.

OR: we just continue on DDNet, break compatibility, and advertise DDNet, using separate master servers which are more secure & reliable, providing a client that is maybe bloated but more secure and active.

So what is it gonna be?

**Comment by Learath2** [comment]
A merge is not the solution I'd go for, teeworlds was never meant to be anything more then a 2d shooter platformer. And I also agree that the DDNet code is a mess. I'd instead like to get a clean version of the DDNet client and server without the DDRace specific features. A fresh base for new mods to be coded on.

The masterserver issue some of you mentioned is easily solvable if teeworlds was willing to accept improvements, a masterserver that operates over HTTP or one that at least has a proper challenge-response mechanism or one that asks for PoW on register would all be possible solutions.

> I didn't read everything here, but I'm on TW-Dev's side. DDNet came, killed almost the whole game, and if it finally takes over tw, it would kill the game entirely. I also don't like some facts about tw itself, but ddnet is a mess (concerning code style, stability and resource comsumption). Sure, it has SDL2 and maybe other little things which could be added to vanilla, but thats it. One thing I've seen was that private hosted servers (whatever gametype) disappeared almost complete right after ddnet appeared. You are right, ddnet has already taken over but thats bad I think. Teeworlds is Teeworlds and not DDNet.
> I'd personally like to make DDNet and THE WHOLE BLOCK COMMUNITY disappear. Why? Because the block community is rude (they are, really) and DDNet has a position where it has too much power. Today we have a good example for those 'powers': The masterservers are being attacked by someone and the ddnet one just blocks everything from outside while DDNet's own servers are still listed. I hope you understand.

@Stitch626 How is it our fault that people don't want to host their own servers? We actively encourage people to host theirs and even help them out with the setup. Yes the DDNet code is a mess but it's also a clear improvement over the teeworlds one feature-wise. DDNet isn't in a position of power because we actively seeked for one. It's in a position of power because as the community gets smaller and smaller people prefer to stay together rather then spread out and play in small groups. Afaik we don't actively stop other servers from registering to the masterserver DDNet hosts, during attacks it's possible that either one of the automatic or the manual firewall rules started blocking out others, which we can't do anything about if no one reports it.

@loru We do our very best to keep the vanilla compatibility at every step of the way so I doubt DDNet players will ever be stuck not being able to connect to vanilla servers or vice-versa.

> I'm against the merge. But I'd welcome a bunch of features DDNet has added. The only thing I would change is the development team, new and fresh people who is up and worthy for the role.

@Sonix- Yes, we are swimming in fresh developers here in this dying community /s

**Comment by lschierbach** [comment]
> How is it our fault that people don't want to host their own servers? We actively encourage people to host theirs and even help them out with the setup. 

This. I don't get the critique. As I did a remake of the old tournament Mod it took less then a few hours for DDNet to host a server. For nothing. I still wonder why they're doing this, as the server is empty 24/7, but saying that DDNet is disrupting progress is just plain BS

**Comment by jxsl13** [comment]
hm, would agree to start a new teeworlds base completely from the ground up with a modelling-process being strictly the first step with lot's of discussions and so on, before even any code is written.

 UML stuff :D maybe. 
The orientation should be both ddnet and teeworlds with maybe the best of both worlds.

**Comment by android272** [comment]
I agree that moddability is something that needs to be worked on. In my opinion, it is the mods and DDNet that keeps TW alive. Unfortunately, compiling TW mods can be a bit tricky at times (this seems to be by design).

**Comment by getkey** [comment]
I'm really glad this is being discussed. I used to mod the game a long time ago (love the decentralized approach, I think it is one of the great assets of the game). I lost a interest about 2 years ago, at the time where v0.7 still looked promising. Teeworlds is the game that I ever loved most, so I would be really sad if it was to die.

I was surprised to see so much activity in DDNet. Also really cool too see old peeps like @heinrich5991 and @def- (and others! :wink:) that I know to be very knowledgeable are doing so much stuff on it.

It's been a while since I last played I might be wrong, and I'm sorry if I am.
However DDNet is made by and oriented towards more hardcore players. I don't think it will do much good to attract new players. And without new players, the game (DDNet and official Teeworlds) will dwindle.

I am curious to hear about who is (or used to) manage/being part of the official Teeworlds organization (and all of what is around it) and what are their plans for the future. If like @teetow they are okay with letting it dying, they might as well let the community take its independence and take the game where it wants.
It is interesting that a few people in this thread criticized DDNet's code quality, so I'd like to hear more what the official maintainers think of it. While I can for sure imagine that it must be worse than the official given the amount of features that got packed into it and the freer development model, but a badly coded game will always be better in my book than no game at all.

What happened after the steam launch? If someone was kind enough to enlighten me, that would be great, since I stopped playing shortly after the release. From whoever put it on Steam, it would also be cool to openly give the community insights about the players from analytics if Steam provides them.

The current UI of Teeworlds looks dated, DDNet or otherwise, and I can imagine that it could be hard to understand/be a bad first experience for new players. (if we had analytics we could test this assumption)

So yeah, to me the most viable option would be a fork of the official Teeworlds that would break backward compatibility if necessary and would be developed conjointly with the DDNet team. It would be **focused on beginners** because they are necessary in an healthy multiplayer game, with a modern rewrite of the UI or whatever it takes to make it appealing to them and of course security fixes.

---

@android272 In my opinion if a fork is made `bam` should be replaced (like it's been in DDNet). It's Magnus' pet project and it's very nifty, but having to install non-standard tooling doesn't help developers to join.

**Comment by heinrich5991** [comment]
> It is interesting that a few people in this thread criticized DDNet's code quality, so I'd like to hear more what the official maintainers think of it. While I can for sure imagine that it must be worse than the official given the amount of features that got packed into it and the freer development model, but a badly coded game will always be better in my book than no game at all.

I think DDNet's code quality is pretty bad in some respects, but I think most of that is code that was inherited from DDRace, new code looks pretty okay, up to Teeworld's levels. DDNet also tried adding tests, so maybe it's even better in some (but fewer) respects.

I think merging DDNet code into Teeworlds should at most be done on a case-by-case basis.

**Comment by jxsl13** [comment]
I don't think that bam is that bad of a tool, compared to the load of work that needs to be put in making a cmake file.

**Comment by oy** [comment]
I guess [this old forum post](https://www.teeworlds.com/forum/viewtopic.php?pid=119733#p119733)  pretty much covers the whole thing.
Besides that, DDNet is a different game which uses Teeworlds' code and master server, but that's about it. A merge doesn't make sense at all...

**Comment by Henningstone** [comment]
![grafik](https://user-images.githubusercontent.com/9981005/42415313-5c00f47a-824a-11e8-9a1e-20b3f8534218.png)

**Comment by H-M-H** [comment]
>  How about passing the stick to people who want this game to progress and nit stagnate.

Well, there is nothing stopping anyone to just fork Teeworlds and get things going again. But it appears there is nobody who can spend all the time and dedication to do so. @necropotame tried to  with https://github.com/teeuniverse but they appear to have lost interest. So as long as nobody steps forward to do all this work I do not see this here going anywhere, sadly.
After all this is a rather small open source game and nobody gets paid for spending their time working on it.

**Comment by loru** [comment]
@H-M-H The whole point of this issue is exactly this… https://github.com/ddnet/ddnet
We never heard of teeuniverse..

Anyway, thank you oy for your contribution. I'm not gonna lie, am a bit disappointed with such an under-detailed answer to my issue, but considering Teeworlds has been dead for years, it's not a surprise, what should we expect, heh.

Good bye Teeworlds, and bon vent DDNet.

**Comment by Rei-Tw** [comment]
hi @oy ,
Sure, games are created & have a "lifetime". But, letting a game like teeworlds dying because of a community that is currently "annoyed" by all attacks by some players, is quite stupid (sorry for the language). We have to improve the netcode, add more stuff on it, for example layer6 stuff like encryption.

We have to change this, but making it only on DDNet would break the compatibility & would be useless.
This game needs at least an improvement on this side before its end.
Regards,
