### ISSUE TITLE
Info change

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1539]
why did you remove info change while ingame? at least make it so you can activate it serverside using the code. imo its useless to remove that feature.

**Comment by MrCosmoX** [comment]
The player name checks have also been removed. It is now possible to have duplicate names and even empty names.

The only logic I can understand is that mods should no longer be allowed to edit players' client info. Which for example is used for the vanilla support of 64 player mods. Because here the ClientID's are swapped with players who are closer to you. Of course this is no longer possible if you can't change the name and clan of the players anymore.

**Comment by oy** [comment]
The reason it got removed was that it was mostly used to annoy other people. And it contradicts the purpose of that feature. If you pick a name you stick to it and don't change it during a game. Otherwise it could be removed in general and be done like matricks suggested - everyone gets a random name/skin.

**Comment by MrCosmoX** [comment]
It would be new to me that people would seriously complain about that. Especially now that obviously a bigger part of the community is against this change. But I understand the reason now.

How about you add the possibility to change the ingame info again. But it leaves up to the server admins e.g. via the config whether it is possible or not. Also deactivated by default. So everyone would be satisfied.

**Comment by oy** [comment]
Well it seems you only need it for the 64 player mods. I'd rather have this #1201 be done, then you would be fine.

**Comment by ChillerDragon** [comment]
@oy as far as i understood #1201 only would help for more spectators ( what is a nice feature ) but doesn't help with more ingame players.
Imo 64 isn't enough but 16 could definitely be increased also for vanilla. What about at least 20 for vanilla? c:

Or at least add the possibility for the modding community to increase the limit.

**Comment by oy** [comment]
16 players is more than enough for the Teeworlds gametypes. It has been raised to 16 to make it possible to have more spectators on the servers. And the original plan was to go back to 12 once the spectators would have been seperated, but I think keeping it by 16 would be good.

**Comment by ChillerDragon** [comment]
@Oy it is not all about the vanilla gametypes. A big part of teeworlds are the modded servers (that should be compatible with the vanilla client, so don't tell us again to just fork the game and create what ever we want). We love this game and we want to extend it without creating our own incompatible fork.
I also miss the slots in vanilla gametypes ( mostly because of spectators that is true ) but i personally love tees and can't get enough of them.
We can keep 16 as default config or even 8 i don't care but allowing people to map big vanilla maps for many tees would be nice.

Or atleast allow the modding scene to hacky add more slots without breaking vanilla support.

**Comment by AlphaSwag** [comment]
@oy  I've been a competitive vanilla player almost all my teeworlds career (10 years) but I disagree with forcing a 16 player limit. It's an essential feature for many tw mods. Even though I'm a hardcore vanilla player and rarely play anything else, I don't see why you would do things that largely negatively affect large communities of other mods, unless there was a benefit to it. Teeworlds is Teeworlds, all these mods are all the same game anyway, no?

**Comment by Sonix-** [comment]
I’m against more than 16 players. Games would get messy the only way i could accept it is for multiple teams gametypes (domination for example). I’m a god level player if that matters (just kidding.. or not :D)

**Comment by ChillerDragon** [comment]
@Sonix- ye we can go for a 16 or even 8 player limit default setting and you don't have to play on chaos servers. The hardcore vanilla scene will probably keep their player limits. But thats no reason to make it impossible for others to increase it.

**Comment by Dune-jr** [comment]
Related: #1574
