### ISSUE TITLE
Armor icons are slightly cropped

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1581]
Cut on the right and the bottom:
![image](https://user-images.githubusercontent.com/355114/47618838-d6b7e580-dad7-11e8-9b66-4aae99873618.png)

**Comment by nheir** [comment]
Looks like it's also the case for the heart icons

**Comment by oy** [comment]
Would be best to fix it in the image, so they don't touch the border. Also the empty heart has a different offset from the top than the filled one.

**Comment by Zatline** [comment]
this is a personal remake of the game.png I done years ago it's pretty close to the original all colors, shapes and sizes are 1:1 the original only difference is the style of these armor and health icons unfortunatly never liked the original, this also is a repost from the discord channel;

![game_](https://user-images.githubusercontent.com/344608/47684456-3e9f2680-dbd3-11e8-8851-98a73a09afe4.png)

>personaly played with it a lot back in the days I think the weapons appear sharper in game if my memory is correct the withe flag was for a new gametype I had in mind calld "hold the flag" it's death match with an objectiv player who holds the flag longest wins

**Comment by Sonix-** [comment]
@Zatline looks good to me, the hp always needed a little retouch in my opinion.
Just a little remark, remove the white flag and also the black background of the empty heart and armour.
Some possibilities:
(your orange shadow looks a bit darker)
![game_edit3](https://user-images.githubusercontent.com/2030615/47722387-9fba0f00-dc52-11e8-807c-e565ad4185c1.png)
![game_edit2](https://user-images.githubusercontent.com/2030615/47722400-a47ec300-dc52-11e8-8338-abb394608f39.png)
![game_edit1](https://user-images.githubusercontent.com/2030615/47722404-a779b380-dc52-11e8-9b28-dac60b46067b.png)

**Comment by Dune-jr** [comment]
@Sonix- cool, I like all of these!

**Comment by oy** [comment]
Should probably use the same colour for armor in the hud and as pickup.

**Comment by Fisico** [comment]
i really like the redesigned hearts and armour. But i agree with oy the pickup color should be identical to the hud color.

**Comment by android272** [comment]
I really like these. The hearts, shields, and damage stars needed a redesign anyway as they have gradients and don't use the same shading as the guns do. Plus these shields are rounder and a lot of the world in Teeworlds is supposed to be round. EX: trees, Tee houses, bushes etc. so these look a lot more teeish. I give my approval once the right colors are picked. When I get home I will make these changes in the graphics redesign @oy and I are working on.

**Comment by Zatline** [comment]
@android272 what graphic redisgn dud everything is there it's all on dropbox stop it! focus on making some new stuff instead can you contact me on Discord I might have a project for you

**Comment by android272** [comment]
@Zatline so I have remade nearly 100% of the Teeworlds art. I did an almost 1 to 1 redraw (basically I traced all the art) as an SVG. The devs did not have the original SVG source files. or at least oy did not, I don't know.  TW 0.6 needed some post-processing done to the assets to look good, TW 0.7 no longer requires this post-processing for assets. The problem is that the 0.6 assets already had this process done to them and cannot be reversed. With the originals being lost someone had to recreate them all. Oy said on the forums one day that 0.7 could not be released without this being done so I volunteered to redraw all the assets. We are working now to finalize these assets.

Clearly 0.7 was shipped before everything was done to take care of some security issues so it still uses 0.6 assets. To see what I mean go into a map that has a Teehouse and look for a second at how horrible the curves are. This is due to the way things were done. Actually, there was an issue about the sun not looking good which is probably due to the same thing.

If you don't mind I would like to use your hearts and shield icons for the new assets as they are more teeish than the old ones.

**Comment by Zatline** [comment]
@android272 it's beocuse the dilate and borderdix thing were applied on the bitmaps back then yes 
now since those ain't needed anymore sure all bitmaps are flawed and had to be updated I totally get that but we can easeily do it by just rendering a fresh bitmap out of the original svg, I'll take care of that, or you can since I'll grand you access shortly but we will not use your remakes!! 
I went trough the folders that you have linked in the tw forum sections and it didn't took long for me to spot flaws in shape in color and shading there is lot of inconsistancy there, can't allow them after all the carefull work Landil, Crisis and me have put into creating and re-creating them the first time, I'm really sorry for that, but I'll literally got nuts if our work get's replaced with a less quality remake, no offense.

You have some incredible potential I'd like you to focus on an actual upcoming theme and help me with all gfx stuff since I'm like the last guy left of the old group, in return I help u refine your your teestyle the way Landil helped me .. this has gone offtopic 🐤

**Comment by Dune-jr** [comment]
The remade graphics need a lot of testing but I believe there were some improvements too. I wouldn't be so quick to discard them.

**Comment by Zatline** [comment]
@Dune-jr sure I'm absolutely open to review all of android's work in detail with him once we exchanged details and check what could be usefull what not and why not etcetera.

**Comment by Dune-jr** [comment]
Well, the issue should only be closed when it is fixed imo. Please include the changes first.

**Comment by Sonix-** [comment]
Yeah leave it open until you make a PR
