### ISSUE TITLE
Please add Scottish Gaelic translation

### ISSUE THREAD

**Issue by gunchleoc** [teeworlds/teeworlds#1621]
I have just brought my translation back to 100% and I noticed that it was never added.

Locale: gd
English name: Scottish Gaelic
Native name: Gàidhlig

Can you please add it?

Thanks!

**Comment by Dune-jr** [comment]
@gunchleoc I'm sorry, 0.7.0 was a bit hasty, we will make sure to add it for 0.7.1

Thank you for your renewed contribution.

**Comment by gunchleoc** [comment]
Thanks!

Any chance that you can add it before the release, so that I can do some testing in-game? I sometimes get context or string truncation issues.

**Comment by Dune-jr** [comment]
@gunchleoc In order to test languages locally, a `scottish_gaelic.json` file has to be added in data/languages/, and the `index.json` file has to be updated.

The former .json file can be generated using the script located here: https://github.com/teeworlds/teeworlds/blob/master/scripts/reconvert_l10n.py
This script requires python3 and `pip3 install polib`.

I have generated it for you: [scottish_gaelic.json.zip](https://github.com/teeworlds/teeworlds/files/2565513/scottish_gaelic.json.zip)
Do not forget to edit `index.json` accordingly.

When testing for string truncation issues, please try different resolutions (especially ratios). Thanks!

**Comment by Dune-jr** [comment]
@gunchleoc Much thanks for adapting your translation and fixing text overflow problems! I have included your last changes at https://github.com/teeworlds/teeworlds-translation
