### ISSUE TITLE
Link to the wiki in readme.txt

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1654]
In order to include build directions, but not to bloat the readme.txt, it could point to https://www.teeworlds.com/?page=docs&wiki=compiling_everything
This page is supposed to be generated from https://github.com/teeworlds/documentation
Maybe the linux section could be updated with a list of packages for popular distribs, too.

**Comment by ChillerDragon** [comment]
👍 and i guess you mean readme.md :p 
Imo the commands for installing the needed packages on debian based systems should be in the readme already because thats mostly the file that people see if they download teeworlds from github.

**Comment by Dune-jr** [comment]
Is `readme.txt` gone?

**Comment by ChillerDragon** [comment]
Ye seems like in 0.7 we moved to markdown instead.

**Comment by ChillerDragon** [comment]
@Dune-jr now you totally confused me haha.
I assume by released ``readme.md`` you mean this file https://github.com/teeworlds/teeworlds/blob/master/readme.md

And by CircleCI you mean the build status?
<img width="335" alt="readme_cicleci" src="https://user-images.githubusercontent.com/20344300/48375622-d10df280-e6c8-11e8-8701-836a03d3c7bb.png">

So i hope the answer to you question is yes? xd

I have no idea what this conversation is...
But i just realized that the [teeworlds CircleCI site](https://circleci.com/gh/teeworlds/teeworlds) still has a circle1 alert even tho we should run circle2 now.

**Comment by Dune-jr** [comment]
@chaosk Circle1 should still be able to build teeworlds, for now. Just not 0.6.

**Comment by ChillerDragon** [comment]
@Dune-jr prior to [this commit](https://github.com/teeworlds/teeworlds/commit/4fa26b739af3f8cf9eed9dd77f7f5dd526094b16) all builds failed on 0.7 master.

And i thought 0.6 is not connected to CircleCI at all because i didn't see a build status or a circle file in the 0.6 branch. But it seems like CircleCI has a [0.6 branch](https://circleci.com/gh/teeworlds/teeworlds/tree/0.6) and it seems to use circle1. I think this should be fixed even tho we upgraded to 0.7. We still had security fixes latly in 0.6 and the Circle page just looks unclean.

**Comment by Dune-jr** [comment]
Oh whoops, I missed the updating commit. Good point.
