### ISSUE TITLE
Damage indicators could distinguish armor damage from health damage

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1715]
Here is a very quick implementation of the idea:

![screenshot_2018-11-24_22-30-44](https://user-images.githubusercontent.com/355114/48973125-ad3b9c80-f038-11e8-957d-6be86fc48c64.png)

I would like to do something more graphically elaborate, while still tiny and teeish (an absorption effect), but I don't have enough time before release.

Now, do you think the slight color difference in the stars should be implemented? Quick thoughts?

Edit: updated screenshot

**Comment by Dune-jr** [comment]
Doesn't seem too popular of an idea, I'll close, then :)

**Comment by sepulzera** [comment]
(I do not think you should close a suggestion just because noone answered within 5 days.)

You shouldn't convey information by color only. And even if you do, it should be intuitive then.

Imagine giving a screenshot just of the middle part of your screen to a teeworlds stranger.
What do you think their conclusion would be?
> Ok, there is an explosion and you got probably hurt (-> eyes of the tee). There are 3 stars, maybe that is the damage you got. One orange star and two yellow? No idea. *- teeworlds stranger*

But it could work out if you colorize the stars accordingly. Orange/red stars could symbolize the lost hearts, silver stars the armor.


![screenshot_damage_indicators](https://user-images.githubusercontent.com/43857716/49508396-e5d24600-f882-11e8-9291-7376b22343f4.jpg)

But be aware that you change existing game mechanics: Now you will know if your opponent has armor left.

**Comment by Dune-jr** [comment]
I closed because 0.7.1 was to be released anyway, and targetting 0.7.2 means more time to do something better looking.

The whole idea behind it was to try to be as visually un-distracting as possible. I'm trying to avoid too much contrast between the stars - not something you keep noticing.

**Comment by sepulzera** [comment]
There is nothing wrong with delaying ideas to later versions, imo.

> I'm trying to avoid too much contrast between the stars

Keep accessibility in mind. If the contrast is too low, some people won't be able to notice it.
If you go for different indicators, then make them sufficient diverse.

Personally, I think that this idea is interesting and worth discussing. 

Should we give the information, that the opponent has no armor left? 
Something worth to try out. 

Could this be implemented by client mods? 
I guess not. But if, why doesn't vanilla teeworlds do?

**Comment by Dune-jr** [comment]
With #1716, this information is now available to the client in 0.7.1-rc (but not yet used, this is only the necessary protocol change).

I also think the idea is interesting and worth discussing, but I would like to come back with something better than a color code before more discussion. I'm focusing on fixing 0.7.1 for now, then I'll open an issue with another, more graphically elaborate proposal.
