### ISSUE TITLE
Implement protocols for client components such as chat, gui and scoreboard for better modding support.

### ISSUE THREAD

**Issue by Ryozuki** [teeworlds/teeworlds#1853]
For the scoreboard, server should be able to tell the client what stats to render, how to order them, how many players, etc. This one shouldn't be hard.

As for the chat, a custom color system + popovers such as (but on the chat):

![image](https://user-images.githubusercontent.com/15859336/49924862-9958bd00-feb7-11e8-90b9-2dac7ff39d74.png)

A UI protocol to draw specific mod GUIs and so on.

I know you want to keep things simple, and you can do so in your admired vanilla gametypes, but modding is more complex, more complex ideas which would look more awesome with more customization support. These are just ideas.

Sorry if i explain myself not clear, but i guess you can see what i pretend here.

I also saw that broadcast colors are disabled by default, which is a sad thing but huh, expected from teewords. (like when standard gametypes filter was on by default)

**Comment by Dune-jr** [comment]
Pop up hints are https://github.com/teeworlds/teeworlds/issues/1834

**Comment by LordSk** [comment]
Colored broadcast have the potential to do a lot good but also a lot of harm (blinking advertising, rainbow text, etc...). Having it disabled by default seems like the correct choice. You wouldn't want new players to experience the potential abuse colors can bring to the table.

Now extending mod support is a very interesting topic indeed, and we can start to think of what would be the correct way to do it. Here is what I propose for now, since you came forward @Ryozuki, can you survey mod makers and sum up what they would want to accomplish with their mods? It could be as simple as: "I want to display an image here", or "I want to know if a client's mouse is hovering that point".

We might then be able to find a solution that pleases most people.

**Comment by fokkonaut** [comment]
i would want the ability to place gun and hammer entities from the code in 0.7. It worked in 0.6 but since WEAPON_X is replaced by PICKUP_X in 0.7 its not possible anymore

**Comment by Dune-jr** [comment]
Gameplay discussions have been moved to the [Development forum](https://www.teeworlds.com/forum/viewforum.php?id=2).
