### ISSUE TITLE
Clock on Scoreboard

### ISSUE THREAD

**Issue by lryjnks** [teeworlds/teeworlds#1861]
A clock that is displayed in the scoreboard so that you don't have to leave the game or display the time on other devices.

**Comment by themisak** [comment]
Yes I also find a clock would be nice, also with option to disable of course

**Comment by fokkonaut** [comment]
ddnet has one, on the top of the screen

**Comment by lryjnks** [comment]
> ddnet has one, at the top of the screen

Yes either that way or the UI team can choose a better place

**Comment by fokkonaut** [comment]
i think we dont need an actual option for it, disabling it using f1 is ok i think.

**Comment by 1stDecadeTW** [comment]
Something like this?

![screenshot_2](https://user-images.githubusercontent.com/44511917/50198017-670feb00-030f-11e9-9b85-039083ec52d1.jpg)

**Comment by lryjnks** [comment]
Looks decent!
Personally, I like it better when the clock is displayed at the top. Like the first or fourth Pic!

**Comment by themisak** [comment]
The 4th picture looks best I think

**Comment by Sonix-** [comment]
I vote for 3rd

**Comment by 1stDecadeTW** [comment]
> I vote for 3rd

I personally like the 3rd option (bottom right clock, maybe the design could be improved) because is intuitive, recognizable and it does not detract from the scoreboard. 

![screenshot_2](https://user-images.githubusercontent.com/44511917/50239479-e3461500-0387-11e9-9f7f-fe65212b8463.jpg)

4th option looks good, but the clock is not a frequently used feature and it shouldn't be as prioritized as the scoreboard and the demo recording information.
![screenshot_1](https://user-images.githubusercontent.com/44511917/50239531-0d97d280-0388-11e9-9381-ffcef503a478.jpg)

**Comment by lryjnks** [comment]
> 4th option looks good, but the clock is not a frequently used feature and it shouldn't be as prioritized as the scoreboard and the demo recording information.

Still my favorite!

**Comment by themisak** [comment]
I vote for 4th :D
