### ISSUE TITLE
Make it possible to not loose the chat when changing map on a server

### ISSUE THREAD

**Issue by themisak** [teeworlds/teeworlds#1902]
At the moment when changing the map on the server all the past chat is lost in the normal chat. You have to press f1 in order to see the chat from before the map change and f1 is not as good looking as the normal chat.

1. It would be much nicer to not loose the chat from before the map change and be able to look at it in normal chat. This Change would make especially sense with the scrollbar also added to look at past chats from issue #1849 

2. ALSO: If you Type a very long message but don't send it yet and the map gets changed everything is lost and you have to Type again. whats written in the chat but not sent yet should be kept.

Hope you like the idea,
cheers

**Comment by ChillerDragon** [comment]
> ALSO: If you Type a very long message but don't send it yet and the map gets changed everything is lost and you have to Type again. whats written in the chat but not sent yet should be kept.

Pressing uparrow to resend the message should fix that issue.

**Comment by lryjnks** [comment]
In my opinion, these are important changes that need to be made!

**Comment by fokkonaut** [comment]
1 is useless, 2 is good

**Comment by sepulzera** [comment]
@fokkonaut Answering an idea with *is useless* is useless. Arguing without any reason is invalid.

1. Should come with a chat limit (if there isn't already one). Otherwise it may consume a lot of memory over time.
2. Is bugging me, too.

**Comment by ChillerDragon** [comment]
@fokkonaut is more a ddrace player and I think the chat problem is more a Vanilla server with map rotation problem most of the players never encounter it. As far as I know only random noobs play on public servers with map rotation. On these servers people mostly don't care about the chat or don't even know how to use it.

Some personal experience: 
I played multiple years of gores and these servers are known for voting new maps a lot and I personally am a very chat active person but I never had any problems with 1. or 2. ( just a side note I want to mention not saying the issue is wrong or bad ).

**Comment by themisak** [comment]
I am not a very frequent chatter but it happened to me multiple times @ChillerDragon

**Comment by savander** [comment]
I like the idea. Chat should be kept for a current server, to the moment when you disconnect. Now it's available at F1 after all, but chat is much clearer and expected place to read messages.

Also, keeping chat messages on map-change sounds great. Should be added

**Comment by Dune-jr** [comment]
When the map change is not due to a vote, it could be useful to have some sort of small marker that lets us know when a map change happened in the chat.

**Comment by oy** [comment]
There could be a client-sided message "map changed to 'xyz'" f.e..

**Comment by Dune-jr** [comment]
Right, good idea
