### ISSUE TITLE
Default sv_inactive_kick to "send to spectators"

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#1906]
We have up to 64 slots now - far enough to make disappear the need to kick afkers.

At least make it not kick *spectators*, that's really annoying.

**Comment by themisak** [comment]
If you want to do it properly I would do it so:

1. Players who are inactive ingame should get moved to spectators, we have enough slots due to the 64 player support (But chatting should not be counted as inactive)

2. Then Player who are also afk in spectators should be kicked. There has to be some kind of mechanism that the the server notices when the a player is in front of his screen oder he is afk. Like if someone is chatting he should not get kicked and if someone moves his mouse he should also not get kicked

**Comment by Dune-jr** [comment]
That already exists afaik, thats `sv_inactivekick 1` right?

**Comment by oy** [comment]
The default value for max clients nad player slots is still 8.

**Comment by sepulzera** [comment]
Btw. you will get kicked if you just spectate someone, without doing any input. That should be removed too imo. That is the spectators functionality at its core.
