### ISSUE TITLE
[Sliders] Can't click to jump to a specific value nor enter that value manually

### ISSUE THREAD

**Issue by Patiga** [teeworlds/teeworlds#2000]
It would be great to just click somewhere on the slider to change a value or manually enter a value.
It feels sloppy the way it is right now.

**Comment by Robyt3** [comment]
How should clicking on a slider behave? In Windows GUI, if you click on a slider, the handle is moved in that direction, about the size of the handle itself. Holding down on the slider moves the handle until it's below the mouse. Or should it instantly snap to the clicked position? I'd prefer the former.

I guess we could adjust the ScrollbarOption to have a small textbox, but I'm not sure we need that, given that we for instance replaced some textboxes with sliders to begin with because editing numbers in a box was inconvenient. If you need a very specific value you could still use the console.

**Comment by Dune-jr** [comment]
> How should clicking on a slider behave? In Windows GUI, if you click on a slider, the handle is moved in that direction, about the size of the handle itself. Holding down on the slider moves the handle until it's below the mouse. Or should it instantly snap to the clicked position? I'd prefer the former.

So do I

> I guess we could adjust the ScrollbarOption to have a small textbox, but I'm not sure we need that, given that we for instance replaced some textboxes with sliders to begin with because editing numbers in a box was inconvenient. If you need a very specific value you could still use the console.

Yeah, agree
