### ISSUE TITLE
Support custom chat commands

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2117]
Would be nice to have better mod support for chat commands. Similar to the remote console that also supports autocompletion for non vanilla commands.

**Comment by AssassinTee** [comment]
I already asked Dune about this, he said it was gamebreaking :o

**Comment by Dune-jr** [comment]
I only said it would require protocol changes (right?).

I am not sure there is a good approach to do what you want. Rcon commands are executed server side, so all you need to send is the command name and the syntax. So far, the client-side commands execute client code. It's not really possible to customize that from the server, especially since the commands aren't just linked to a f1 command but instead do smart stuff with the player names (need to find the ID from it, and player names are not unique).

I think what @ChillerDragon wants is server-executed commands that can be sent from the client via the chat. It's quite a bit different than an extension "for non vanilla commands' though, because so-called "vanilla commands" don't do that, they don't send anything to the server. So then you would have different kind of commands mashed together (client and server), and they would need to be visually different.

I originally did this command system because I'm tired of having to go in the menus to add friend/mute people or to tab endlessly to whisper people on crowded servers. Of course we already have stuff to improve the user experience with modified servers, like loading the rcon commands, so I personally don't see why not do that with player commands as well. Here are a few concerns though:

- right now there are no indications that a command menu is there, because it is completely optional
- it must be made clear what commands are server-side and what commands are client-side
- gotta solve the compatibility issues

**Comment by AssassinTee** [comment]
> right now there are no indications that a command menu is there, because it is completely optional
This is True, since its a new feature and optional
> it must be made clear what commands are server-side and what commands are client-side
The Client sided commands are white (textcolor), simply make the server sided ones red?
> gotta solve the compatibility issues
backwards compatiblity shouldn't be a problem, since the feature is optional. Other client's just wouldn't see the new commands as a list, but would still be able to use them. The hole feature is just visually

**Comment by jxsl13** [comment]
Me gusta. I want this! As long as 0.7.x is young, it should handle some protocol changes. If this issue is kept lying around, it will never be added, what's rather sad, as it has lots of potential.

**Comment by fokkonaut** [comment]
Yes. And I would get rid of the clientside chat commands, as they can block serverside chat commands.

**Comment by Dune-jr** [comment]
They don't block them, if you exit the command menu by pressing Escape.

**Comment by AssassinTee** [comment]
most servers have always implemented something like `/info` and `/help` and maybe `/cmdlist`, this is something a lot of devs do, would be nice to have it as a standard provided by teeworlds

**Comment by Dune-jr** [comment]
The server could communicate a list of commands like this:

![image](https://user-images.githubusercontent.com/355114/63536556-2870a700-c514-11e9-8b65-72a16df6b9ed.png)

This list of commands would be limited in size but could be refreshed by the server depending on the status of the player. There could be a flag for client-side auto-completion for player names.
