### ISSUE TITLE
Randomize lms spawns

### ISSUE THREAD

**Issue by Sonix-** [teeworlds/teeworlds#2138]
i've played some lms games today, and noticed that 90% if not 100% i always spawned in the same position (lts1).. they should be random in LMS to make it fair and balanced

**Comment by sepulzera** [comment]
Imo the spawn positions should be randomized for all gametypes.

For Domination all possible startup positions are calculated and then pseudo-randomized picked based on the Servertick. 
https://github.com/teeworlds-domination/domination/blob/188b75d802e9c7c3834ba680f4fd74b41e79c4f7/src/game/server/gamemodes/dom.cpp#L250

That yields two positive changes:
- the very same player will spawn on a different spawn for each try
- it takes all spawnpositions into consideration

Alternatively, the order of the player for the spawn calculation could be randomized only. But that would still always pick top left for the first player etc.

**Comment by Dune-jr** [comment]
Tees should still spawn away from ennemies in non-survival gametypes

**Comment by sepulzera** [comment]
> Tees should still spawn away from ennemies in non-survival gametypes

I agree on that and furthermore would suggest to keep this for LMS, too.
But those are two separate concerns:
1. How the first spawn position is picked: Currently, top left. Imo that should be randomized, to make the game a bit more interesting and allow different starting positions. (That would possibly also affect the spawning when all characters die at the same time, e. g. 1on1).
2. How you define *away from enemies*. Vanilla would only pick the most distant spawn. Domination uses a little tolerance here (30 %). Two spawns that are somewhat equally most far away are being considered. Because... why should after all my opponent choose my spawning position?
