### ISSUE TITLE
master server seems to be vulnerable to whatever

### ISSUE THREAD

**Issue by jxsl13** [teeworlds/teeworlds#2168]
it seems that the 0.7 master servers can be influenced in such a way, that individual servers can be blacklisted, seemingly banned and or delisted, I guess, especially masterserver 1 and masterserver 3.
I don't know the background, but highly believe that is is possible, as I was told that someone is capable of doing so.

**Comment by MrCosmoTW** [comment]
I don't think the masterservers have a vulnerability that can be exploited to block servers. The 0.7 network protocol no longer allows IP spoofing. The reason master1 and master3 would be particularly affected in 0.7 is probably because they are the only masters in 0.7.

I don't know how you came to the conclusion that this is possible, but the only way I know of to deliberately block a server from a master is via the hosting server. We are currently using special firewall rules due to the DDoS attacks that have been running for weeks to block the attacks. It's well known that you can spoof a certain IP address and flood packets to the server. This leads both by our firewall rules and mostly by the hosting providers to an automatic blocking of the IP address.

At least for master1 is the case, if you have the concrete suspicion that it is blocked by a vulnerability outside of the Teeworlds Masterserver, then you can also write to me privately.

**Comment by TeeMuLTIII** [comment]
Hello @jxsl13 i don't know if you were the person who joined the conversation earlier. The conversation was about the fact that individual servers/networks can be excluded should they not adhere to the rules of [Server Rules](https://www.teeworlds.com/forum/viewtopic.php?id=10442) hold. As mentioned in this conversation, these can be reported in the forum or on IRC. Should any further questions be open, please don't hesitate to contact me.

**Comment by MeskalinMaskulin** [comment]
I can confirm what @MrCosmoTW said: It's probably the hosting providers blocking IPs because of spoofing attacks.
At least that is what I observed in 0.6 times, I am not aware of an easy fix for that issue however.

**Comment by oy** [comment]
Closing this as there's not enough info available.
