### ISSUE TITLE
Bug - Clientside? - Joining Spectators increases death count.

### ISSUE THREAD

**Issue by jxsl13** [teeworlds/teeworlds#2219]
Joining Spectators increases death count.
Seems to be a client side thing. As I don't know much about clients, I'm opening this issue here.

Edit:
Tested on some random vanilla server as well.

**Comment by fokkonaut** [comment]
Yes. Kills and Deaths for the scoreboard are clientside (which is in my opinion very bad, the server should send those as snap items, because mods can use them in another way then, for example i have kills and deaths saved in my accounts, and could display them there for example. Also, I have used the gametimer for race time, and when it resets, the kills and deaths reset too.)
