### ISSUE TITLE
Maximum ping filter goes to "0" upon erasal of the field

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2267]
When you remove the value of the number field "Maximum ping" in the server browser, it resets to 0, which results in no server being shown, and that's a bit hard to troubleshoot. Make it so it resets to 999

**Comment by fokkonaut** [comment]
Make the reset to 999 happen when the box is not selected anymore, otherwise its weird to type a number in it without needing to leave a last number in

**Comment by Robyt3** [comment]
Maybe use a scrollbar option (between 20 and 999) instead of an editbox? Like this:

![asdsadsadsad](https://user-images.githubusercontent.com/23437060/71765665-e14de600-2ef7-11ea-8b5e-4a1d793e5f30.JPG)

I find it quite cumbersome to enter a value, especially when it resets itself to 999 when you remove it or go above 999 while entering.

Also the server browser could show how many total vs. filtered servers there are, or show an additional message when the filters exclude all servers, so players figure out why no servers are shown for them.

**Comment by Dune-jr** [comment]
@Robyt3 I agree with both points
