### ISSUE TITLE
Set the dynamic camera off by default or improve the current dynamic camera

### ISSUE THREAD

**Issue by ghost** [teeworlds/teeworlds#240]
See the discussion here: http://www.teeworlds.com/forum/viewtopic.php?id=6851

**Comment by abck** [comment]
With the upcoming 0.7 release, i would like to discuss this topic again.

The most players are still playing with dyn. cam turned off. 
Newbies often don't look through all the possible settings, they just play with default ones. If they don't like the game in the first some minutes they simply quit playing because of the wrong perception Teeworlds may be hard to play because of the dyn cam that one needs to get used to first. Therefore disabling dyn cam. by default could make it easier for new players to get into the game, since getting used to the hook is hard enough.

I'd say either turn it off by default or explain both to new players (with pictues and some text) and let them pick what they like better.

**Comment by oy** [comment]
Well beginners usually just run around, jump and shoot - a wider view comes in handy there.

**Comment by heinrich5991** [comment]
We could try to make some usability statistics. No idea how to gather them though.

**Comment by oy** [comment]
Yeah probably hard to realize that.

**Comment by Sonix-** [comment]
Letting the players choose between dynamic and static camera on first launch would be an ideal solution

**Comment by heinrich5991** [comment]
Options on startup should be minimized. People should be able to just jump into a game, even the current configuration is a little much...

**Comment by oy** [comment]
> Letting the players choose between dynamic and static camera on first launch would be an ideal solution

Well, the user doesn't know what dynamic/static camera 'means' - how it differs ingame - on first start.

**Comment by Sonix-** [comment]
@heinrich5991 well, there should be a "Getting Started" dialog on first start, skippable ofcourse, in order to explain at least the basics to the player.
@oy a brief explanation/example of what are those cameras to the user would be nice

**Comment by oy** [comment]
Doubt that it would help, the user actually has to test it to make up his/her mind. On a first launch the user has no clue how it looks like/behaves - might not even know it's 2D.

**Comment by heinrich5991** [comment]
@Sonix- In-game hints should be preferred, most games do that.
