### ISSUE TITLE
Sanitize max player/client count in server browser

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2444]
Example:
![image](https://user-images.githubusercontent.com/355114/73288589-2d3c3400-41f3-11ea-955a-cf8869ce644a.png)

**Comment by Robyt3** [comment]
That server is sending invalid server info with CServerInfo::m_MaxPlayers being zero, even thou there are human players on the server. Maybe they have a bug somewhere in their code.

Would be fixed by dropping the invalid server info by adding the missing check `m_MaxPlayers < m_NumPlayers` to [this if](https://github.com/teeworlds/teeworlds/blob/0b0bc2400c447abf4701c2f2ad83068693d1e84c/src/engine/client/client.cpp#L934).

**Comment by Dune-jr** [comment]
Should we drop the server or cap it to a sane value?

**Comment by fokkonaut** [comment]
Drop it

**Comment by oy** [comment]
Yeah, drop them like the other invalid infos.
