### ISSUE TITLE
Sliders are buggy

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2498]
When holding on a slider bar in the settings and moving the mouse onto another slider, it will be buggy since both are triggered a bit.

**Comment by Robyt3** [comment]
Yeah, I also noticed that when implementing the other scroll and slider related stuff, but I couldn't come up with an easy solution using the hot and active item pointers.

Might make more sense to clamp the mouse position to the slider bar, when interacting with it, instead of clamping the slider handle position to the bar. 

On Windows 10, scrollbars don't work or just glitch around, when the mouse is outside, which seems even less useful.

**Comment by Dune-jr** [comment]
I cannot reproduce this on my win7... When you hold onto a slider, other sliders aren't triggered?

**Comment by fokkonaut** [comment]
It only happens if your mouse goes over another slider while you still have the other one grabbed. Like @Robyt3 suggested, clamping the mouse to the slider would fix it.

**Comment by Dune-jr** [comment]
Now, I can reproduce (linux).
