### ISSUE TITLE
[Editor2] Asset manager: add image with file explorer

### ISSUE THREAD

**Issue by LordSk** [teeworlds/teeworlds#2550]
**Part 1**
Extract the important part from the `DoFileSelect()` function.
![image](https://user-images.githubusercontent.com/294603/79048913-9a6f3b00-7c20-11ea-96e0-06e41e6d94a3.png)

Basically remove the preview and bottom part. Have it return true when selecting a new file.
Then update the `RenderPopupMapLoad()` and `RenderPopupMapSave()` accordingly (move the code from the `DoFileSelect()` function). 

**Part 2**
Make an "Add Image" popup in the Asset Manager, to load and add an image. Preview the image on select (on the right side of the popup). Remove the temporary text input that was used to add images.

**Comment by Learath2** [comment]
Issues don't close unless the commit hits master I guess, I wonder if issues can be tied to other branches.

**Comment by Dune-jr** [comment]
[That is not possible](https://stackoverflow.com/questions/28326899/close-issue-on-github-pull-request-to-non-master-branch)

**Comment by Learath2** [comment]
Well yes but I think the fact that the first part was only necessary because of the second part.

<details>If @LordSk still wants the first part someone else can do it. I'm not willing to put my name on a commit with dozens of duplicated lines of not only rendering but logic that can easily go out of sync during an update or refactoring.</details>
