### ISSUE TITLE
Server address is not saved when connecting through console commands

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2558]
Previously (0.7.4), when using `connect <ip>` to connect to a server, the IP address would be memorized in the server address bar, and a disconnect/connect would let us rejoin the server.

On master, pressing disconnect and reconnecting with `Return` sends us to the last server we went to using the GUI; this is a change in behaviour.

**Comment by Learath2** [comment]
#2544 maybe?

**Comment by Robyt3** [comment]
We now save two different addresses for Internet and LAN. Which one do you want to change, when you e.g. connect to the server while being in the settings menu?

I tried adding a ConchainConnect to update the UI addresses to implement #2544, before coming up with the current solution. However that wouldn't work when the client is started with a connect command in a config or command line, because of the special handling that connect gets, so I opted for something that would work in all cases.

@ChillerDragon seems to prefer the new workflow. I don't really mind either way.

**Comment by Dune-jr** [comment]
> @ChillerDragon seems to prefer the new workflow. I don't really mind either way.

Well if the goal was that

> >  so no old workflow breaks

it did not succeed...

> We now save two different addresses for Internet and LAN. Which one do you want to change, when you e.g. connect to the server while being in the settings menu?

Wouldn't it be easy to tell if it's a server on the Internet or on LAN?

**Comment by Robyt3** [comment]
> Wouldn't it be easy to tell if it's a server on the Internet or on LAN?

Should be somehow possible with a ConchainConnect calling CServerBrowser::Find.

But doesn't that mean that the connect command should also switch the browser tab from e.g. LAN to Internet if you connect to an Internet server? Otherwise disconnecting and connecting with enter would still use the address from the from LAN tab.

However, supporting the initial connect would be too hacky for me. Instead, the command manager should buffer certain commands, until everything is initialized, and only then invoke the respective command chain.

**Comment by oy** [comment]
No need to check if the server is within the list. Would just set the address bar of the tab that is active.
