### ISSUE TITLE
Chat doesn't scroll on overly long strings

### ISSUE THREAD

**Issue by Learath2** [teeworlds/teeworlds#2662]
While working on #2521 I noticed that the bounds of the selection wouldn't always within the visible bounds (between `m_Input.GetString() + m_ChatStringOffset` and `m_Input.GetCursorOffset()-m_ChatStringOffset`)  , which made no sense. Turns out `KEY_LEFT` doesn't actually cause `m_InputUpdate` so `chat.cpp:L903` which is supposed to catch this, doesn't. To observe for yourself, input the repeating pattern `W_` until it no longer fits and move your cursor to the start.

Not quite sure how best to address this, `KEY_LEFT` isn't really a change so returning `true` from `CLineInput::ProcessInput` sounds wasteful and not really appropriate.

**Comment by Robyt3** [comment]
Returning `true` from `CLineInput::ProcessInput` seem correct, because something did actually change that now needs handling. If you don't want everything updated at once, you could return an int instead, composed of flags that specify what exactly changed. `CConsole` does not even use the returned value of `ProcessInput` at all.
