### ISSUE TITLE
New broadcast shadow looks horrible

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2793]
The size got bigger and now it just looks awful...
![image](https://user-images.githubusercontent.com/35420825/97241203-aacbb980-17f0-11eb-8225-486b19680dbb.png)

comparing to an older client:
![image](https://user-images.githubusercontent.com/35420825/97241217-b919d580-17f0-11eb-9c28-99593e969caa.png)

maybe the fade should be stronger and the shadow itself should get smaller again.

**Comment by SoulyVEVO** [comment]
i gotta agree, maybe making shadow more visible wasnt a bad idea by itself but this is too much

**Comment by TsFreddie** [comment]
Looks like the server is using three lines with two empty lines. With one line it shouldn't look like that. We can make shadow fit the text horizontally as well.

But i'd say we should wait for the new textrender then we can just use the boundingbox.

**Comment by TsFreddie** [comment]
We can also try to make shadow ignore empty lines.

**Comment by Robyt3** [comment]
You can try making it more transparent. I settled for this gradient because anything less dark is not as readable as it could be on some map backgrounds. Anything with a darker top makes the top edge or even the left or right edges explicitly visible to me, which I wanted to avoid.

Fade on the old client had almost no effect readability and only gave you an indication that the broadcast was active at all.

I'm not sure if there is any way to make the gradient colored rounded corners not look weird with this size. IMO we could also get rid of this custom fade alltogether and just add a flat round rect with CORNER_T and correctly calculated size.

**Comment by l-ouis** [comment]
both look bad lol why is there such an ugly gradient
