### ISSUE TITLE
ScreenShots not working

### ISSUE THREAD

**Issue by xBeefyOreo** [teeworlds/teeworlds#2826]
when i want to do screenshot i click on keyboard "PrtSc" and windows does not take a screenshot of the game but a screenshot of the window behind the game, i.e. in my case the desktop or discord or something else ...

**Comment by Dune-jr** [comment]
This is expected behaviour. Screenshots in Teeworlds can be bound to a dedicated key, by default f10, though you can change it. You will find the screenshot in the `screenshots` folder of your %USER%\AppData\Roaming\Teeworlds folder on Windows.

This being said, it may be counter-intuitive for users of modern software, and maybe we should *also* bind to the PrintScreen key by default, and *also* copy to clipboard.

**Comment by Rei-Tw** [comment]
It may work better also if you're not in fullscreen mode whenever you use PrtSc.
