### ISSUE TITLE
My gametype cant display

### ISSUE THREAD

**Issue by ST-Chara** [teeworlds/teeworlds#2984]
My gametype cannot be displayed in the server list, but it shows successful registration
Help me!

**Comment by Robyt3** [comment]
You changed a file that determines the netversion hash (https://github.com/teeworldsCNFun/teeworlds-infclassRliar/commit/089e24a6fb05e3bbf23f94e2f55cf4847674808d changes gamecore which influences the netversion hash).

A different netversion hash makes your server technically incompatible with default clients, because it might have different physics.

In your case it's fine, as you don't change any physics. You'll need to send a forced (hard-coded) netversion hash instead of using the generated one. First obtain the original netversion hash from `src/generated/nethash.c` by compiling an unmodded version of the source code. Then hard code that hash in your `src/game/version.h`. Similar to how it's done for 0.7 currently:

https://github.com/teeworlds/teeworlds/blob/f35da54b6f2c5f9fd4bbd4559f887ccf8f8cc526/src/game/version.h#L7-L8

(but insert your own version and netversion hash)

**Comment by ST-Chara** [comment]
ok thanks
