### ISSUE TITLE
Create mute system same as kick system

### ISSUE THREAD

**Issue by JulianAssange** [teeworlds/teeworlds#378]
Create mute system same as kick system

**Comment by ChillerDragon** [comment]
![screenshot_2020-12-22_15-11-23](https://user-images.githubusercontent.com/20344300/102897504-619e8b80-4468-11eb-9bf1-0ab1ad52c248.png)

Agree the client side mute feature is very nice and should always be used over global mute. But sadly most players are more aware of the kick feature than the mute feature so it is barley used. Would be nice if an admin could avoid a kick vote by muting players that are not willing to change their ddrace binds for example.

**Comment by jxsl13** [comment]
Should he added, same as votebanning people (banning from starting kickvotes). 
More less radical choices to keep the players playing while having them blocked from talking shit and voting shit.
Often people abuse kickvotes in order to get attention.
In order to break them psychologically and still maintain a full server, it is best to mute them for a while and voteban them for a longer period of time.
I have done this many times and it works perfectly fine.
If they start flaming after being votebanned or muted for 5-10 minutes, you kan ban them for 5 - 30 minutes without any comment and either they never join again or they rejoin and follow the rules of being nice.
