### ISSUE TITLE
Add slopes

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#93]
It seems it was planned to add slopes in tw: http://www.teeworlds.com/forum/viewtopic.php?pid=4063#p4063

Is there still a plan to add them? I think it would be a great feature.

**Comment by Irradius** [comment]
i think needs do better the movebox, testbox and related functions

**Comment by pielover88888** [comment]
Since the published binaries are windows only, and the source seems to be gone, here's a video of the slopes: http://piecode.tk/video/uploads/?search=teeworlds%20slopes

"so i thought that a corner, can't be considered a stable ground to be able jump from it" ~CarmineZ
I personally think this is a bad idea, because if you land on the corner of a normal tile (in 0.6, not sure about 0.7) you get your jump back, and corners are corners. Corners should be consistent with eachother regardless of how they are produced, because to the player..corners are corners.

**Comment by MegaManSec** [comment]
I have the source code of carminez final creation on a hard drive
somewhere.  I'll attempt to find it some time, so people can see the code.

**Comment by Henningstone** [comment]
Arent't this his sources?: [Teeworlds Forum](https://www.teeworlds.com/forum/viewtopic.php?id=7447)
Or is that wrong?

**Comment by oy** [comment]
CarmineZ's slope mod isn't the one mentioned here https://www.teeworlds.com/forum/viewtopic.php?pid=110876#p110876

**Comment by Irradius** [comment]
In fact, I wanted to download your version to compare with mine, but I have not found... have you the source or the windows version (corresponding to Landil topic)?

**Comment by oy** [comment]
Didn't code the version in Landil's topic and unfortunately don't have a copy of that source.

**Comment by pielover88888** [comment]
@Henningstone those source links are dead/404 now, though.

**Comment by MegaManSec** [comment]
Here's the source code for CarmineZ' slopes: https://github.com/MegaManSec/CarmineZ-Teeworlds-Slope

**Comment by H-M-H** [comment]
In case you are still interested in slopes I put this here https://www.teeworlds.com/forum/viewtopic.php?id=10476 to github and merged it with current 0.7: https://github.com/H-M-H/teeworlds/tree/slopes_merge_try
(without merge: https://github.com/H-M-H/teeworlds/tree/slopes)
Binaries: https://github.com/H-M-H/teeworlds/releases/tag/slopes-0.7
(you need to add data folder manually atm as make_release.py does not work properly)

**Comment by Dune-jr** [comment]
Gameplay discussions have been moved to the [Development forum](https://www.teeworlds.com/forum/viewforum.php?id=2).
