### ISSUE TITLE
New Menu bugs/changes

### ISSUE THREAD

**Issue by cinaera** [teeworlds/teeworlds#988]
Bugs:
- 'heart', 'lock' and 'tee' symbol should each have their own column
- If there are no server in "All" because of the filter the "All"-tab is gone and u cant set the filter back
- Remove the right side filters and add the friendlist (:
- It shouldn't be able to deactivate 'Standard gametype' in the 'Standard gametype'-tab

Wishes(?):
- Add the missing bind options in the settings menu for 'ready_change', 'add_demomarker', etc.
- Seeing the Menubackground should be independent from High Details on/off
- Maybe menu_night/day should circle up to the current time like 6pm to 6am/6am to 6pm or sth like that
  and if u want to have another map u could set it, in the settings

**Comment by cinaera** [comment]
Add an option disable background map in the menu

**Comment by Henningstone** [comment]
• Some dialogs are too small for the text to fit in (e.g. the "wrong version" dialog, shown when client version differs from server version)
• I want my exit button back :3 [see #1316], cause we've got to click on such different positions so often to exit

**Comment by Dune-jr** [comment]
> @cinaera 
Bugs:
- [x] 'heart', 'lock' and 'tee' symbol should each have their own column
- [x] If there are no server in "All" because of the filter the "All"-tab is gone and u cant set the filter back
- [x] Remove the right side filters and add the friendlist (:
*I think that is fixed?*
- [x] It shouldn't be able to deactivate 'Standard gametype' in the 'Standard gametype'-tab

- [ ] Additional one: Join a server, go into settings menu via esc Let the server crash -> Setting tabs still shown in the menu http://i.solidfiles.net/2e910c8e7b.png

Wishes(?):
- [x] Add the missing bind options in the settings menu for 'ready_change', 'add_demomarker', etc.
- [ ] Seeing the Menubackground should be independent from High Details on/off
*Could be fixed, does it have to?*
- [x] Maybe menu_night/day should circle up to the current time like 6pm to 6am/6am to 6pm or sth like that
- [x] and if u want to have another map u could set it, in the settings

- [x] Add an option disable background map in the menu


> @magnet 
- [x] Lack of clear filter in the server list (and easily accessible current players). (currently I can't get the filter to work at all).
- [x] Lack of server tabs to split Internet / LAN / Favourites (horrible ergonomics).
- [x] Settings are more confusing than ever
- [x] In-game UI, why not, has to be reworked.
*Kinda done, unless there are more specific complaints?*
- [x] Main menu is useless: It should be possible to skip it with an option
- [ ] The map editor is not built on the same UI design, and should not be accessible through the main menu until its design is edited to fit.
*Should it be fixed? I mean, this needs a whole editor rework, this is #1301*
- [x] No "Quit" button in the server browser.

> @heinrich5991 
- [x] Especially when you want to quit you have to click on very different positions. Before everything except the 'yes' was in the top right corner.

> @Henningstone 
- [x] Some dialogs are too small for the text to fit in (e.g. the "wrong version" dialog, shown when client version differs from server version)
Fixed by #1843
- [x] I want my exit button back :3 [see #1316], cause we've got to click on such different positions so often to exit

**Comment by oy** [comment]
> Additional one: Join a server, go into settings menu via esc Let the server crash -> Setting tabs still shown in the menu http://i.solidfiles.net/2e910c8e7b.png

Tried it. Works. So seems to be fixed.

**Comment by oy** [comment]
> Seeing the Menubackground should be independent from High Details on/off

Already fixed by bdfbf0019013f91c49801bab3335275765231222

**Comment by oy** [comment]
> The map editor is not built on the same UI design, and should not be accessible through the main menu until its design is edited to fit.

That has it's own issue #1301.
Closing.
